apiVersion: v1
kind: Service
metadata:
  name: videoin
  namespace: xw
spec:
  type: NodePort # 服务类型
  ports:
  - port: 8000 # Service端口
    protocol: UDP # 协议
    targetPort: 8000  # 容器端口
    nodePort: 30027  # 对外暴露的端口，可以指定
  selector:
    app: pku-sender # 指定关联Pod的标签
